inspiradanacomputacao/tecnologistas-contra-bolsonaro

README.md
Como o primeiro parágrafo termina com _…forjar um Brasil que_, a ideia é que a lista que segue tenha cada item começando com um verbo para dar continuidade a ideia do primeiro parágrafo.
Também dei uns pitacos em locais que achei que dava para utilizar linguagem neutra sem complexificar demais o texto.
=> Inicia frases com verbo para manter a consistência

README.md
Closes #10
Closes #14
Closes #17
Closes #19
Closes #21
Closes #24
Closes #26
Closes #27
Closes #28
=> Adiciona assinaturas que chegaram por Issues

README.md
=> Adição de meu nome

README.md
Assim podemos ver facilmente quantas pessoas/coletivos assinaram.
=> Substitui lista não ordenada por lista numerada

README.md
=> Inclusão de Volnei Filho

README.md
=> Assinaturas via issues

README.md
Adicionando meu nome ao manifesto.
=> ✨feature: Add meu nome

README.md
=> ADD Cristina Mantovani - @crismantovani

README.md
O mínimo que eu posso fazer.
Nem sei como a gente chegou aqui :shrug:
=> Adicona Janil Garcia à lista

README.md
=> Adiciona Somatório

README.md
=> Minha assinatura

README.md
add meu nome Jean Carlos Izepon.
=> assinar manifesto

README.md
=> Otávio Cartaxo - Assinatura

README.md
=> Add @ztzandre

README.md
=> docs(readme): include Paulo Gonçalves

README.md
=> Fabiano Santos Florentino

README.md
=> Luiz Felipe Amadeu

README.md
Update readme with Carlos Barros - @ocarlosbarros
=> docs(readme): signing ocarlosbarros

README.md
This PR adds Halley's signature to the Readme file.
=> feature: adds Halley's signature

README.md
Assinando.
BTW, percebi que o editor de markdown do github numera todas as linhas automagicamente, o que pode causar PRs com mil mudanças acidentais...
=> Adicionar assinatura do Capi Etheriel

README.md
=> Nova assinatura victorfranz

README.md
Por um país com menos desigualdade, mais respeito por todos e confiança na ciência. ⭐
=> Adicionar assinatura @brunolmfg

README.md
Signed-off-by: Bruno FS Ciconelle <fsouza.bruno@gmail.com>
=> Assinado p/ Bruno Ciconelle

README.md
Trabalhadores do mundo, uni-vos! Não temos nada a perder a não ser nossos grilhões
=> Adicionando assinatura Rafael Kato

README.md
=> Adiciona Cleiver nas assinaturas

README.md
=> Add assinatura.

README.md
Corrigindo meu @ no Twitter :)
=> Corrige meu @diegocoxta no nome.

README.md
Adicionado meu nome à lista. 
F0r4 B0ls0n4r0!
=> Adicionar meu nome

README.md
=> adicionando meu nome

README.md
Adding the following signatures:
- Rafael Barros Pires (my own)
- Bruno Umbelino (closes #258)
- Ana Maria Silva (closes #262)
- Maria Fernanda Souza (closes #266)
- Elon Lima Bezerra (closes #268)
=> add my signature and other signatures requested on issues

README.md
=> Adicionando Matheus Ricelly

README.md
Adiciona meu nome, José Teles Maciel, à lista de assinantes.
=> Adiciona nome a lista de assinantes

README.md
=> Adiciona assinatura: @jbsilva

README.md
Insert Jackson Osvaldo (Backend Developer)
=> Insert Jackson Osvaldo (Backend Developer)

README.md
Adiciona assinatura - Paulo Siqueira
=> Adiciona assinatura - Paulo Siqueira
